// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/jsonproduct.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProductsProtoLibrary.Grpc {

  /// <summary>Holder for reflection information generated from Protos/jsonproduct.proto</summary>
  public static partial class JsonproductReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/jsonproduct.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JsonproductReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQcm90b3MvanNvbnByb2R1Y3QucHJvdG8SFFByb2R1Y3RzUHJvdG9MaWJy",
            "YXJ5Ghxwcm90b3MvcHJvZHVjdG1lc3NhZ2VzLnByb3RvGhxnb29nbGUvYXBp",
            "L2Fubm90YXRpb25zLnByb3RvMqQCChJQcm9kdWN0SnNvblNlcnZpY2USjAEK",
            "E1VuYXJ5UHJvZHVjdExpc3RpbmcSKS5Qcm9kdWN0c1Byb3RvTGlicmFyeS5G",
            "aWx0ZXJDcml0ZXJpYUlucHV0GiEuUHJvZHVjdHNQcm90b0xpYnJhcnkuUHJv",
            "ZHVjdExpc3QiJ4LT5JMCISISL2FwaS9wcm9kdWN0cy9saXN0OgEqYghwcm9k",
            "dWN0cxJ/ChZVbmFyeUdldFByb2R1Y3REZXRhaWxzEiIuUHJvZHVjdHNQcm90",
            "b0xpYnJhcnkuRGV0YWlsc0lucHV0Gh0uUHJvZHVjdHNQcm90b0xpYnJhcnku",
            "UHJvZHVjdCIigtPkkwIcEhovYXBpL3Byb2R1Y3RzL3twcm9kdWN0X2lkfUIc",
            "qgIZUHJvZHVjdHNQcm90b0xpYnJhcnkuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProductsProtoLibrary.Grpc.ProductmessagesReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
