// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/products.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProductsProtoLibrary.Grpc {

  /// <summary>Holder for reflection information generated from Protos/products.proto</summary>
  public static partial class ProductsReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/products.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQcm90b3MvcHJvZHVjdHMucHJvdG8SFFByb2R1Y3RzUHJvdG9MaWJyYXJ5",
            "Ghxwcm90b3MvcHJvZHVjdG1lc3NhZ2VzLnByb3RvMvMDCg5Qcm9kdWN0U2Vy",
            "dmljZRJjChNVbmFyeVByb2R1Y3RMaXN0aW5nEikuUHJvZHVjdHNQcm90b0xp",
            "YnJhcnkuRmlsdGVyQ3JpdGVyaWFJbnB1dBohLlByb2R1Y3RzUHJvdG9MaWJy",
            "YXJ5LlByb2R1Y3RMaXN0ElsKFlVuYXJ5R2V0UHJvZHVjdERldGFpbHMSIi5Q",
            "cm9kdWN0c1Byb3RvTGlicmFyeS5EZXRhaWxzSW5wdXQaHS5Qcm9kdWN0c1By",
            "b3RvTGlicmFyeS5Qcm9kdWN0ElYKEEdldFByb2R1Y3RMaXN0U1MSHS5Qcm9k",
            "dWN0c1Byb3RvTGlicmFyeS5Mb3RTaXplGiEuUHJvZHVjdHNQcm90b0xpYnJh",
            "cnkuUHJvZHVjdExpc3QwARJiChBHZXRQcm9kdWN0TGlzdENTEikuUHJvZHVj",
            "dHNQcm90b0xpYnJhcnkuRmlsdGVyQ3JpdGVyaWFJbnB1dBohLlByb2R1Y3Rz",
            "UHJvdG9MaWJyYXJ5LlByb2R1Y3RMaXN0KAESYwoPR2V0UHJvZHVjdHNCb3Ro",
            "EikuUHJvZHVjdHNQcm90b0xpYnJhcnkuRmlsdGVyQ3JpdGVyaWFJbnB1dBoh",
            "LlByb2R1Y3RzUHJvdG9MaWJyYXJ5LlByb2R1Y3RMaXN0KAEwAUIcqgIZUHJv",
            "ZHVjdHNQcm90b0xpYnJhcnkuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProductsProtoLibrary.Grpc.ProductmessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
