// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/products.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ProductsProtoLibrary.Grpc {
  public static partial class ProductService
  {
    static readonly string __ServiceName = "ProductsProtoLibrary.ProductService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput> __Marshaller_ProductsProtoLibrary_FilterCriteriaInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProductsProtoLibrary.Grpc.FilterCriteriaInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ProductsProtoLibrary.Grpc.ProductList> __Marshaller_ProductsProtoLibrary_ProductList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProductsProtoLibrary.Grpc.ProductList.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ProductsProtoLibrary.Grpc.DetailsInput> __Marshaller_ProductsProtoLibrary_DetailsInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProductsProtoLibrary.Grpc.DetailsInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ProductsProtoLibrary.Grpc.Product> __Marshaller_ProductsProtoLibrary_Product = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProductsProtoLibrary.Grpc.Product.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ProductsProtoLibrary.Grpc.LotSize> __Marshaller_ProductsProtoLibrary_LotSize = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ProductsProtoLibrary.Grpc.LotSize.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> __Method_UnaryProductListing = new grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnaryProductListing",
        __Marshaller_ProductsProtoLibrary_FilterCriteriaInput,
        __Marshaller_ProductsProtoLibrary_ProductList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ProductsProtoLibrary.Grpc.DetailsInput, global::ProductsProtoLibrary.Grpc.Product> __Method_UnaryGetProductDetails = new grpc::Method<global::ProductsProtoLibrary.Grpc.DetailsInput, global::ProductsProtoLibrary.Grpc.Product>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnaryGetProductDetails",
        __Marshaller_ProductsProtoLibrary_DetailsInput,
        __Marshaller_ProductsProtoLibrary_Product);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ProductsProtoLibrary.Grpc.LotSize, global::ProductsProtoLibrary.Grpc.ProductList> __Method_GetProductListSS = new grpc::Method<global::ProductsProtoLibrary.Grpc.LotSize, global::ProductsProtoLibrary.Grpc.ProductList>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetProductListSS",
        __Marshaller_ProductsProtoLibrary_LotSize,
        __Marshaller_ProductsProtoLibrary_ProductList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> __Method_GetProductListCS = new grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "GetProductListCS",
        __Marshaller_ProductsProtoLibrary_FilterCriteriaInput,
        __Marshaller_ProductsProtoLibrary_ProductList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> __Method_GetProductsBoth = new grpc::Method<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GetProductsBoth",
        __Marshaller_ProductsProtoLibrary_FilterCriteriaInput,
        __Marshaller_ProductsProtoLibrary_ProductList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ProductsProtoLibrary.Grpc.ProductsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProductService</summary>
    [grpc::BindServiceMethod(typeof(ProductService), "BindService")]
    public abstract partial class ProductServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ProductsProtoLibrary.Grpc.ProductList> UnaryProductListing(global::ProductsProtoLibrary.Grpc.FilterCriteriaInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ProductsProtoLibrary.Grpc.Product> UnaryGetProductDetails(global::ProductsProtoLibrary.Grpc.DetailsInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetProductListSS(global::ProductsProtoLibrary.Grpc.LotSize request, grpc::IServerStreamWriter<global::ProductsProtoLibrary.Grpc.ProductList> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ProductsProtoLibrary.Grpc.ProductList> GetProductListCS(grpc::IAsyncStreamReader<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetProductsBoth(grpc::IAsyncStreamReader<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput> requestStream, grpc::IServerStreamWriter<global::ProductsProtoLibrary.Grpc.ProductList> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProductService</summary>
    public partial class ProductServiceClient : grpc::ClientBase<ProductServiceClient>
    {
      /// <summary>Creates a new client for ProductService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProductService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProductServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProductServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ProductsProtoLibrary.Grpc.ProductList UnaryProductListing(global::ProductsProtoLibrary.Grpc.FilterCriteriaInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnaryProductListing(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ProductsProtoLibrary.Grpc.ProductList UnaryProductListing(global::ProductsProtoLibrary.Grpc.FilterCriteriaInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UnaryProductListing, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ProductsProtoLibrary.Grpc.ProductList> UnaryProductListingAsync(global::ProductsProtoLibrary.Grpc.FilterCriteriaInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnaryProductListingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ProductsProtoLibrary.Grpc.ProductList> UnaryProductListingAsync(global::ProductsProtoLibrary.Grpc.FilterCriteriaInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UnaryProductListing, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ProductsProtoLibrary.Grpc.Product UnaryGetProductDetails(global::ProductsProtoLibrary.Grpc.DetailsInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnaryGetProductDetails(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ProductsProtoLibrary.Grpc.Product UnaryGetProductDetails(global::ProductsProtoLibrary.Grpc.DetailsInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UnaryGetProductDetails, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ProductsProtoLibrary.Grpc.Product> UnaryGetProductDetailsAsync(global::ProductsProtoLibrary.Grpc.DetailsInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnaryGetProductDetailsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ProductsProtoLibrary.Grpc.Product> UnaryGetProductDetailsAsync(global::ProductsProtoLibrary.Grpc.DetailsInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UnaryGetProductDetails, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ProductsProtoLibrary.Grpc.ProductList> GetProductListSS(global::ProductsProtoLibrary.Grpc.LotSize request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductListSS(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ProductsProtoLibrary.Grpc.ProductList> GetProductListSS(global::ProductsProtoLibrary.Grpc.LotSize request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetProductListSS, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> GetProductListCS(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductListCS(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> GetProductListCS(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_GetProductListCS, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> GetProductsBoth(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProductsBoth(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList> GetProductsBoth(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GetProductsBoth, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProductServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProductServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ProductServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UnaryProductListing, serviceImpl.UnaryProductListing)
          .AddMethod(__Method_UnaryGetProductDetails, serviceImpl.UnaryGetProductDetails)
          .AddMethod(__Method_GetProductListSS, serviceImpl.GetProductListSS)
          .AddMethod(__Method_GetProductListCS, serviceImpl.GetProductListCS)
          .AddMethod(__Method_GetProductsBoth, serviceImpl.GetProductsBoth).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProductServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UnaryProductListing, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(serviceImpl.UnaryProductListing));
      serviceBinder.AddMethod(__Method_UnaryGetProductDetails, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ProductsProtoLibrary.Grpc.DetailsInput, global::ProductsProtoLibrary.Grpc.Product>(serviceImpl.UnaryGetProductDetails));
      serviceBinder.AddMethod(__Method_GetProductListSS, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ProductsProtoLibrary.Grpc.LotSize, global::ProductsProtoLibrary.Grpc.ProductList>(serviceImpl.GetProductListSS));
      serviceBinder.AddMethod(__Method_GetProductListCS, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(serviceImpl.GetProductListCS));
      serviceBinder.AddMethod(__Method_GetProductsBoth, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::ProductsProtoLibrary.Grpc.FilterCriteriaInput, global::ProductsProtoLibrary.Grpc.ProductList>(serviceImpl.GetProductsBoth));
    }

  }
}
#endregion
